// models/balanceSheet.js
export default function BalanceSheetModel(sequelize, DataTypes) {
  return sequelize.define(
    "balance_sheet_balance_sheet",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },

      // FIX: TEXT → STRING(50)
      symbol: {
        type: DataTypes.STRING(50),
        allowNull: true,
      },

      col_unknown: { type: DataTypes.TEXT, allowNull: true },

      // All year/date columns remain TEXT
      Mar_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2018: { type: DataTypes.TEXT, allowNull: true },
      Mar_2017: { type: DataTypes.TEXT, allowNull: true },
      Mar_2021: { type: DataTypes.TEXT, allowNull: true },
      Mar_2025: { type: DataTypes.TEXT, allowNull: true },
      Mar_2015: { type: DataTypes.TEXT, allowNull: true },
      Mar_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2023: { type: DataTypes.TEXT, allowNull: true },
      Mar_2016: { type: DataTypes.TEXT, allowNull: true },
      Mar_2022: { type: DataTypes.TEXT, allowNull: true },
      Mar_2014: { type: DataTypes.TEXT, allowNull: true },
      Mar_2020: { type: DataTypes.TEXT, allowNull: true },
      Sep_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2011: { type: DataTypes.TEXT, allowNull: true },
      Jun_2022: { type: DataTypes.TEXT, allowNull: true },
      Dec_2012: { type: DataTypes.TEXT, allowNull: true },
      Dec_2011: { type: DataTypes.TEXT, allowNull: true },
      Dec_2015: { type: DataTypes.TEXT, allowNull: true },
      Dec_2018: { type: DataTypes.TEXT, allowNull: true },
      Dec_2019: { type: DataTypes.TEXT, allowNull: true },
      Dec_2020: { type: DataTypes.TEXT, allowNull: true },
      Dec_2013: { type: DataTypes.TEXT, allowNull: true },
      Dec_2021: { type: DataTypes.TEXT, allowNull: true },
      Dec_2016: { type: DataTypes.TEXT, allowNull: true },
      Dec_2017: { type: DataTypes.TEXT, allowNull: true },
      Dec_2014: { type: DataTypes.TEXT, allowNull: true },
      Jun_2024: { type: DataTypes.TEXT, allowNull: true },
      Jun_2019: { type: DataTypes.TEXT, allowNull: true },
      Jun_2014: { type: DataTypes.TEXT, allowNull: true },
      Jun_2016: { type: DataTypes.TEXT, allowNull: true },
      Jun_2020: { type: DataTypes.TEXT, allowNull: true },
      Jun_2018: { type: DataTypes.TEXT, allowNull: true },
      Jun_2021: { type: DataTypes.TEXT, allowNull: true },
      Jun_2025: { type: DataTypes.TEXT, allowNull: true },
      Jun_2015: { type: DataTypes.TEXT, allowNull: true },
      Jun_2017: { type: DataTypes.TEXT, allowNull: true },
      Jun_2023: { type: DataTypes.TEXT, allowNull: true },
      Mar_2013: { type: DataTypes.TEXT, allowNull: true },
      Mar_2010: { type: DataTypes.TEXT, allowNull: true },
      Mar_2007: { type: DataTypes.TEXT, allowNull: true },
      Mar_2009: { type: DataTypes.TEXT, allowNull: true },
      Mar_2006: { type: DataTypes.TEXT, allowNull: true },
      Mar_2008: { type: DataTypes.TEXT, allowNull: true },
      Mar_2012: { type: DataTypes.TEXT, allowNull: true },
      Sep_2021: { type: DataTypes.TEXT, allowNull: true },
      Sep_2013: { type: DataTypes.TEXT, allowNull: true },
      Sep_2016: { type: DataTypes.TEXT, allowNull: true },
      Sep_2022: { type: DataTypes.TEXT, allowNull: true },
      Sep_2012: { type: DataTypes.TEXT, allowNull: true },
      Dec_2006: { type: DataTypes.TEXT, allowNull: true },
      Dec_2005: { type: DataTypes.TEXT, allowNull: true },
      Sep_2015: { type: DataTypes.TEXT, allowNull: true },
      Sep_2014: { type: DataTypes.TEXT, allowNull: true },
      Mar_2003: { type: DataTypes.TEXT, allowNull: true },
      Mar_2004: { type: DataTypes.TEXT, allowNull: true },
      Sep_2018: { type: DataTypes.TEXT, allowNull: true },
      Dec_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2002: { type: DataTypes.TEXT, allowNull: true },
      Dec_2023: { type: DataTypes.TEXT, allowNull: true },
      Dec_2022: { type: DataTypes.TEXT, allowNull: true },
      Dec_2007: { type: DataTypes.TEXT, allowNull: true },
      Dec_2008: { type: DataTypes.TEXT, allowNull: true },
      Dec_2009: { type: DataTypes.TEXT, allowNull: true },
      Jun_2011: { type: DataTypes.TEXT, allowNull: true },
      Jun_2010: { type: DataTypes.TEXT, allowNull: true },
      Dec_2010: { type: DataTypes.TEXT, allowNull: true },
      Sep_2023: { type: DataTypes.TEXT, allowNull: true },
      Sep_2019: { type: DataTypes.TEXT, allowNull: true },
      Sep_2020: { type: DataTypes.TEXT, allowNull: true },
      Sep_2017: { type: DataTypes.TEXT, allowNull: true },
    },
    {
      tableName: "balance_sheet_balance_sheet",
      timestamps: false,
      freezeTableName: true,
    }
  );
}
