// models/quarterlyResults.js
export default function QuarterlyResultsModel(sequelize, DataTypes) {
  return sequelize.define(
    'quarterly_results_quarterly_results',
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },

      // FIX: TEXT → STRING(50), remove primaryKey
      symbol: { type: DataTypes.STRING(50), allowNull: true },

      col_unknown: { type: DataTypes.TEXT, allowNull: true },

      // All date/year columns remain TEXT
      Sep_2024: { type: DataTypes.TEXT, allowNull: true },
      Jun_2022: { type: DataTypes.TEXT, allowNull: true },
      Jun_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2025: { type: DataTypes.TEXT, allowNull: true },
      Jun_2025: { type: DataTypes.TEXT, allowNull: true },
      Sep_2023: { type: DataTypes.TEXT, allowNull: true },
      Mar_2023: { type: DataTypes.TEXT, allowNull: true },
      Sep_2022: { type: DataTypes.TEXT, allowNull: true },
      Jun_2023: { type: DataTypes.TEXT, allowNull: true },
      Dec_2023: { type: DataTypes.TEXT, allowNull: true },
      Dec_2022: { type: DataTypes.TEXT, allowNull: true },
      Mar_2024: { type: DataTypes.TEXT, allowNull: true },
      Dec_2024: { type: DataTypes.TEXT, allowNull: true },
      Dec_2021: { type: DataTypes.TEXT, allowNull: true },
      Jun_2021: { type: DataTypes.TEXT, allowNull: true },
      Mar_2022: { type: DataTypes.TEXT, allowNull: true },
      Sep_2021: { type: DataTypes.TEXT, allowNull: true },
      Jun_2018: { type: DataTypes.TEXT, allowNull: true },
      Jun_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2019: { type: DataTypes.TEXT, allowNull: true },
      Sep_2018: { type: DataTypes.TEXT, allowNull: true },
      Dec_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2020: { type: DataTypes.TEXT, allowNull: true },
      Dec_2018: { type: DataTypes.TEXT, allowNull: true },
      Sep_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2021: { type: DataTypes.TEXT, allowNull: true },
      Dec_2011: { type: DataTypes.TEXT, allowNull: true },
      Mar_2006: { type: DataTypes.TEXT, allowNull: true },
      Jun_2007: { type: DataTypes.TEXT, allowNull: true },
      Jun_2006: { type: DataTypes.TEXT, allowNull: true },
      Mar_2009: { type: DataTypes.TEXT, allowNull: true },
      Mar_2007: { type: DataTypes.TEXT, allowNull: true },
      Dec_2007: { type: DataTypes.TEXT, allowNull: true },
      Mar_2008: { type: DataTypes.TEXT, allowNull: true },
      Dec_2008: { type: DataTypes.TEXT, allowNull: true },
      Sep_2008: { type: DataTypes.TEXT, allowNull: true },
      Dec_2006: { type: DataTypes.TEXT, allowNull: true },
      Jun_2008: { type: DataTypes.TEXT, allowNull: true },
      Sep_2006: { type: DataTypes.TEXT, allowNull: true },
      Sep_2007: { type: DataTypes.TEXT, allowNull: true },
      Jun_2020: { type: DataTypes.TEXT, allowNull: true },
      Dec_2020: { type: DataTypes.TEXT, allowNull: true },
      Sep_2020: { type: DataTypes.TEXT, allowNull: true },
      Jun_2016: { type: DataTypes.TEXT, allowNull: true },
      Mar_2015: { type: DataTypes.TEXT, allowNull: true },
      Mar_2016: { type: DataTypes.TEXT, allowNull: true },
      Jun_2015: { type: DataTypes.TEXT, allowNull: true },
      Dec_2014: { type: DataTypes.TEXT, allowNull: true },
      Sep_2015: { type: DataTypes.TEXT, allowNull: true },
      Dec_2015: { type: DataTypes.TEXT, allowNull: true },
      Sep_2016: { type: DataTypes.TEXT, allowNull: true },
      Mar_2017: { type: DataTypes.TEXT, allowNull: true },
      Jun_2017: { type: DataTypes.TEXT, allowNull: true },
      Dec_2016: { type: DataTypes.TEXT, allowNull: true },
      Sep_2013: { type: DataTypes.TEXT, allowNull: true },
      Sep_2014: { type: DataTypes.TEXT, allowNull: true },
      Jun_2014: { type: DataTypes.TEXT, allowNull: true },
      Dec_2013: { type: DataTypes.TEXT, allowNull: true },
      Mar_2014: { type: DataTypes.TEXT, allowNull: true },
    },
    {
      tableName: 'quarterly_results_quarterly_results',
      timestamps: false,
      freezeTableName: true,
    }
  );
}
